[book]
authors = ["pintergreg"]
multilingual = false
src = "src"
title = "Jegyzet"
description = "Szoftverfejlesztés multinacionális vállalatoknál"

[rust]
edition = "2018"

[output.html]
mathjax-support = true
additional-js = ["context-cards.js", "mermaid-init.js", "mermaid.min.js", "d3.5.16.0.js", "markmap-lib.transform.min.js", "markmap-lib.view.min.js", "markmap-init.js", "quizdown/quizdown.js", "quizdown/quizdown-init.js"]
# additional-css = ["quizdown/fix.css"]
# additional-css = ["jsmind.css"]
# git-repository-url = "https://github.com/SzFMV2020-Tavasz/handout"

[output.html.fold]
enable = true
level = 1

# [preprocessor.toc]
# command = "mdbook-toc"
# renderer = ["html"]
#
# [preprocessor.plantuml]
# command = "mdbook-plantuml -l"

# [output.epub]

# [output.linkcheck]
# follow-web-links = false
# traverse-parent-directories = false
# user-agent = "Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
